services:
  postgres:
    container_name: runebingo_postgres
    image: postgres:17
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    env_file:
      - .env

  redis:
    container_name: runebingo_redis
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redisdata:/data
    env_file:
      - .env

volumes:
  pgdata:
  redisdata:
