/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "signInWithEmail": {
            "userNotFound": string;
            "userDisabled": string;
        };
        "signUpWithEmail": {
            "emailAlreadyExists": string;
            "usernameAlreadyExists": string;
        };
        "verifyAuthCode": {
            "invalidOrExpired": string;
            "accountDeleted": string;
        };
        "roles": {
            "admin": string;
            "moderator": string;
            "user": string;
        };
    };
    "bingo-participant": {
        "kickBingoParticipant": {
            "bingoNotFound": string;
            "bingoParticipantNotFound": string;
            "forbidden": string;
        };
        "searchBingoParticipants": {
            "bingoNotFound": string;
        };
        "updateBingoParticipant": {
            "bingoNotFound": string;
            "bingoParticipantNotFound": string;
            "teamNotFound": string;
            "cannotSetOwnerRole": string;
            "forbidden": string;
        };
        "leaveBingo": {
            "bingoNotFound": string;
            "notParticipant": string;
            "ownerCannotLeave": string;
            "forbidden": string;
        };
        "transferOwnership": {
            "bingoNotFound": string;
            "notOwner": string;
            "targetParticipantNotFound": string;
            "targetNotParticipant": string;
            "forbidden": string;
        };
        "activity": {
            "kicked": {
                "title": string;
                "deletedTileCompletions": string;
            };
            "left": {
                "title": string;
            };
            "ownershipTransferred": {
                "title": string;
            };
            "updated": {
                "title": string;
                "role": string;
                "teamName": string;
            };
        };
    };
    "bingo-team": {
        "searchBingoTeams": {
            "bingoNotFound": string;
        };
    };
    "bingo": {
        "createBingo": {
            "titleNotUnique": string;
            "forbidden": string;
            "startDateBeforeEndDate": string;
            "registrationDateAfterStartDate": string;
            "activeBingoAlreadyExists": string;
            "startDateAfterEndDate": string;
        };
        "findById": {
            "notFound": string;
        };
        "updateBingo": {
            "bingoNotFound": string;
            "forbidden": string;
            "titleNotUnique": string;
            "startDateAfterEndDate": string;
            "endDateBeforeStartDate": string;
            "registrationDateAfterStartDate": string;
            "statusRestricted": string;
            "tileDeletionNotConfirmed": {
                "singular": string;
                "plural": string;
            };
        };
        "deleteBingo": {
            "bingoNotFound": string;
            "forbidden": string;
        };
        "cancelBingo": {
            "bingoNotFound": string;
            "forbidden": string;
            "alreadyCanceled": string;
        };
        "searchBingoActivities": {
            "bingoNotFound": string;
            "forbidden": string;
        };
        "startBingo": {
            "bingoNotFound": string;
            "forbidden": string;
            "notPending": string;
            "endDateBeforeNow": string;
            "tilesNotPresent": string;
            "participantsNotAssignedToTeams": string;
        };
        "endBingo": {
            "bingoNotFound": string;
            "forbidden": string;
            "notOngoing": string;
        };
        "resetBingo": {
            "bingoNotFound": string;
            "forbidden": string;
            "notCanceled": string;
            "startDateBeforeToday": string;
            "startDateBeforeMaxRegistrationDate": string;
            "endDateBeforeStartDate": string;
        };
        "activity": {
            "created": {
                "title": string;
            };
            "updated": {
                "title": string;
                "body": {
                    "language": string;
                    "title": string;
                    "description": string;
                    "private": string;
                    "width": string;
                    "height": string;
                    "fullLineValue": string;
                    "startDate": string;
                    "endDate": string;
                };
            };
            "started": {
                "title": string;
                "titleEarly": string;
                "body": {
                    "endDate": string;
                };
            };
            "ended": {
                "title": string;
                "titleEarly": string;
            };
            "deleted": {
                "title": string;
            };
            "canceled": {
                "title": string;
            };
            "reset": {
                "title": string;
                "body": {
                    "startDate": string;
                    "endDate": string;
                    "maxRegistrationDate": string;
                    "deletedTiles": string;
                    "deletedTeams": string;
                    "deletedParticipants": string;
                };
            };
            "cancelBingo": {
                "bingoNotFound": string;
                "forbidden": string;
                "alreadyCanceled": string;
            };
            "findBingoByBingoId": {
                "bingoNotFound": {
                    "all": string;
                    "participating": string;
                    "nonParticipating": string;
                };
            };
            "formatBingoActivities": {
                "title": string;
            };
        };
        "entity": {
            "language": string;
            "title": string;
            "description": string;
            "private": string;
            "width": string;
            "height": string;
            "fullLineValue": string;
            "startDate": string;
            "endDate": string;
            "maxRegistrationDate": string;
        };
        "status": {
            "pending": string;
            "ongoing": string;
            "completed": string;
            "canceled": string;
        };
        "tile": {
            "listBingoTiles": {
                "bingoNotFound": string;
            };
            "findBingoTileByCoordinates": {
                "bingoNotFound": string;
                "tileNotFound": string;
            };
            "createOrEditBingoTile": {
                "bingoNotFound": string;
                "badCoordinates": string;
                "forbidden": string;
                "missingFieldsOnCreate": string;
                "mediaNotFound": string;
                "itemNotFound": string;
                "invalidImageUrl": string;
            };
            "deleteBingoTile": {
                "bingoNotFound": string;
                "badCoordinates": string;
                "forbidden": string;
                "tileNotFound": string;
            };
            "moveBingoTile": {
                "bingoNotFound": string;
                "badCoordinates": string;
                "sameCoordinates": string;
                "forbidden": string;
                "tileNotFound": string;
            };
            "activity": {
                "set": {
                    "title": string;
                    "body": {
                        "title": string;
                        "description": string;
                        "value": string;
                        "free": {
                            "true": string;
                            "false": string;
                        };
                        "completionMode": string;
                        "mediaAdded": string;
                        "mediaRemoved": string;
                        "items": string;
                    };
                };
                "deleted": {
                    "title": string;
                };
                "moved": {
                    "title": string;
                };
                "swapped": {
                    "title": string;
                };
            };
        };
        "formatBingoActivities": {
            "title": string;
        };
        "findBingoByBingoId": {
            "bingoNotFound": {
                "all": string;
                "participating": string;
                "nonParticipating": string;
            };
        };
    };
    "email": {
        "verificationEmail": {
            "subject": string;
            "body": string;
            "cta": string;
        };
    };
    "general": {
        "language": {
            "en": string;
            "fr": string;
        };
        "system": string;
        "error": {
            "unexpected": string;
        };
    };
    "media": {
        "validation": {
            "noFileUploaded": string;
            "tooLarge": string;
            "invalidType": string;
            "mimeTypeMismatch": string;
        };
    };
    "session": {
        "createSessionForUser": {
            "userDisabled": string;
            "forbidden": string;
        };
        "setSessionCurrentBingo": {
            "sessionNotFound": string;
            "sessionSignedOut": string;
            "cantSetCurrentBingo": string;
            "bingoNotFound": string;
        };
        "signOutSessionByUuid": {
            "forbidden": string;
        };
    };
    "user": {
        "createUser": {
            "emailAlreadyExists": string;
            "usernameAlreadyExists": string;
            "forbidden": string;
        };
        "findByUsername": {
            "notFound": string;
        };
        "searchUsers": {
            "invalidStatus": string;
        };
        "searchUserActivities": {
            "userNotFound": string;
            "forbidden": string;
        };
        "updateUser": {
            "userNotFound": string;
            "usernameAlreadyExists": string;
            "forbidden": string;
        };
        "formatUserActivities": {
            "userNotFound": string;
        };
        "activity": {
            "created": {
                "title": {
                    "self": string;
                    "other": string;
                };
            };
            "updated": {
                "title": {
                    "self": string;
                    "other": string;
                };
                "body": {
                    "username": string;
                    "language": string;
                    "role": string;
                };
            };
        };
    };
    "validation": {
        "notEmpty": string;
        "invalidEmail": string;
        "username": {
            "noSpecialCharacters": string;
            "invalidLength": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
